# frozen_string_literal: true

source "https://rubygems.org"

# gem "rubocop"
# gem "rubocop-packaging"
# gem "rubocop-performance"
# gem "rubocop-rspec"
# gem "rubocop-shopify"
# gem "rubocop-thread_safety"

gem "ruby-lsp"
# gem "ruby-lsp-rails"
# gem "ruby-lsp-rspec"
