-- [[ Config Harpoon ]]

-- local map = vim.api.nvim_set_keymap
-- map("n", "<leader>haf", '<CMD>::lua require("harpoon.mark").add_file()<CR>', { desc = '[H]arpoon [A]dd [F]ile' })
-- map("n", "<leader>htm", '<CMD>::lua require("harpoon.ui").toggle_quick_menu()<CR>', { desc = '[H]arpoon [T]oggle [M]enu' })
-- map("n", "<leader>hgn", '<CMD>::lua require("harpoon.ui").nav_next()<CR>', { desc = '[H]arpoon [G]o [N]ext' })
-- map("n", "<leader>hgp", '<CMD>::lua require("harpoon.ui").nav_prev()<CR>', { desc = '[H]arpoon [G]o [P]revious' })
--
-- map("n", "<leader>hgh", '<CMD>::lua require("harpoon.ui").nav_file(1)<CR>', { desc = '[H]arpoon [G]o File 1' })
-- map("n", "<leader>hgj", '<CMD>::lua require("harpoon.ui").nav_file(2)<CR>', { desc = '[H]arpoon [G]o File 2' })
-- map("n", "<leader>hgk", '<CMD>::lua require("harpoon.ui").nav_file(3)<CR>', { desc = '[H]arpoon [G]o File 3' })
-- map("n", "<leader>hgl", '<CMD>::lua require("harpoon.ui").nav_file(4)<CR>', { desc = '[H]arpoon [G]o File 4' })
