-- [[ Configure Mini Packages ]]
require('mini.bracketed').setup()
-- require('mini.animate').setup({
--   cursor = {
--     enable = false,
--   },
--   scroll = {
--     enable = true,
--   },
--   resize = {
--     enable = false,
--   },
--   open = {
--     enable = false,
--   },
--   close = {
--     enable = false,
--   },
-- })

-- require('mini.indentscope').setup({
--   symbol = '║',
-- })
